#!/usr/bin/env ruby

require 'rgen/instantiator/default_xml_instantiator'
require 'rgen/environment'
require 'rgen/template_language'
require './server_model'
require './logic_checker'
require './validator'
require 'nokogiri'

class XML
  attr_accessor :deviceConfig
end

if ARGV.empty? or ARGV.length > 1
	puts "Usage: " + $0 + " <config.xml>"
	exit 1
end

if !File.exists?(ARGV[0])
	puts "Error: XML configuration file does not exist."
	exit 1
end	

schema = Nokogiri::XML::Schema(File.read('schema.xsd'))
document = Nokogiri::XML(File.read(ARGV[0]))

schema.validate(document).each do |e|
	puts e.message
	exit 1
end

if not document.root.name === 'deviceConfig'
	puts "\n<deviceConfig> not defined as root node\n\n"
	exit 1	
end

env = RGen::Environment.new
inst = RGen::Instantiator::DefaultXMLInstantiator.new(env, ServerModel, true)
inst.instantiate_file(ARGV[0])

MODEL = XML.new
MODEL.deviceConfig = env.find(:class => ServerModel::DeviceConfig).first

TEMPLATES_DIR = "templates/"
OUTPUT_DIR = "./"

def generateCode
  tc = RGen::TemplateLanguage::DirectoryTemplateContainer.new([ServerModel], OUTPUT_DIR)
  tc.load(TEMPLATES_DIR)
  tc.expand('root::Root', :for => MODEL, :indent => 0)
end

val = Validator.new
if not val.validate(MODEL.deviceConfig)
	puts "\n"; exit 1
end

lc = LogicChecker.new
if not lc.checkLogic(MODEL.deviceConfig)
	puts "\n"; exit 1
end

generateCode

puts "\nServer has been successfully generated.\n\n"
